[features]
seeds = false

[provider]
cluster = "localnet"
wallet = "/Users/danielpavel/.config/solana/devnet-wallet-1.json"

[programs.localnet]
boync_anchor_program = "BJbJMqNcTPazBQTbSuPXVz2dZz7u1Vxb5w4TvACxEB3B"

[programs.devnet]
boync_anchor_program = "BJbJMqNcTPazBQTbSuPXVz2dZz7u1Vxb5w4TvACxEB3B"

[programs.mainnet]
boync_anchor_program = "BJbJMqNcTPazBQTbSuPXVz2dZz7u1Vxb5w4TvACxEB3B"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
start = "yarn run ts-node app/client/main.ts"

[workspace]
members = [
  "programs/boync-anchor-program/program",
  "programs/token-metadata/program",
]