[features]
seeds = false
[programs.localnet]
boync_anchor_program = "EkvnvRY2prU1sJpVLHBk5qsNMXBryaZeMVacRSE1pcZM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/danielpavel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
