[features]
seeds = false
[programs.localnet]
boync_anchor_program = "CTNouVLjqMCabPFdDDoinhfuFLRH5hY5PxoQHsBf6drF"

[programs.devnet]
boync_anchor_program = "CTNouVLjqMCabPFdDDoinhfuFLRH5hY5PxoQHsBf6drF"

[programs.mainnet]
boync_anchor_program = "CTNouVLjqMCabPFdDDoinhfuFLRH5hY5PxoQHsBf6drF"

[registry]
url = "https://anchor.projectserum.com"

[provider]
#cluster = "localnet"
cluster = "devnet"
#wallet = "/Users/danielpavel/.config/solana/id.json"
wallet = "/Users/danielpavel/.config/solana/devnet-wallet-1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
start = "yarn run ts-node app/client/main.ts"
