[features]
seeds = false
[programs.localnet]
boync_anchor_program = "75umXMeZ2xX72AGGM4PgHBSi7UVawU1sQnRakHr64p6g"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/danielpavel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
start = "yarn run ts-node app/client/main.ts"
